In [78]:
import pandas as pd

In [79]:
df = pd.read_csv('BTC_ETH_LTC_Jul0621_Jul0622_1h.csv')

In [80]:
df.head()

,OpenTime,LTC-USD_Open,LTC-USD_High,LTC-USD_Low,LTC-USD_Close,LTC-USD_Volume,CloseTime,LTC-QuoteAssetVolume,LTC-NumberOfTrades,LTC-TBBAV,...,BTC-USD_Open,BTC-USD_High,BTC-USD_Low,BTC-USD_Close,BTC-USD_Volume,BTC-QuoteAssetVolume,BTC-NumberOfTrades,BTC-TBBAV,BTC-TBQAV,BTC-ignore
0,2022-01-01 00:00:00,146.2,149.6,146.1,149.0,16967.766,2022-01-01 00:59:59.999,2.507842e+06,7483.0,9216.637,...,46216.93,46731.39,46208.37,46656.13,1503.33095,6.987999e+07,38608.0,806.06536,3.746216e+07,0.0
1,2022-01-01 01:00:00,149.0,149.7,148.2,148.2,11771.338,2022-01-01 01:59:59.999,1.752459e+06,4497.0,6021.605,...,46656.14,46949.99,46574.06,46778.14,943.81539,4.412715e+07,31872.0,491.18067,2.296327e+07,0.0
2,2022-01-01 02:00:00,148.2,148.7,148.0,148.1,5862.752,2022-01-01 02:59:59.999,8.699672e+05,2118.0,2331.696,...,46778.14,46928.94,46721.96,46811.77,485.16860,2.272067e+07,24364.0,206.35113,9.662607e+06,0.0
3,2022-01-01 03:00:00,148.1,148.4,147.7,147.8,6659.564,2022-01-01 03:59:59.999,9.860645e+05,2112.0,3991.914,...,46811.77,46916.63,46760.12,46813.20,562.88971,2.636326e+07,19882.0,248.28212,1.162938e+07,0.0
4,2022-01-01 04:00:00,147.8,148.0,146.7,146.8,8878.487,2022-01-01 04:59:59.999,1.308191e+06,2604.0,4468.986,...,46813.21,46887.33,46591.23,46711.05,861.88389,4.027204e+07,23357.0,397.53563,1.857540e+07,0.0

In [81]:
def sma(data, window):
    return (data.rolling(window = window).mean())

def bollinger_band(data, sma, window, ntsd):
    std = data.rolling(window = window).std()
    upper_band = sma + std * ntsd
    lower_band = sma - std * ntsd
    
    return upper_band, lower_band

In [82]:
symbols = ['BTC', 'ETH', 'LTC']

In [83]:
nstd = 3

for symbol in symbols:
    df[f'{symbol}_sma'] = sma(df[f'{symbol}-USD_Open'],20)
    df[f'{symbol}_upper_band'], df[f'{symbol}_lower_band'] = bollinger_band(df[f'{symbol}-USD_Open'], df[f'{symbol}-USD_Open'], 20, nstd)

In [84]:
df.dropna(inplace=True)

In [85]:
df.head()

,OpenTime,LTC-USD_Open,LTC-USD_High,LTC-USD_Low,LTC-USD_Close,LTC-USD_Volume,CloseTime,LTC-QuoteAssetVolume,LTC-NumberOfTrades,LTC-TBBAV,...,BTC-ignore,BTC_sma,BTC_upper_band,BTC_lower_band,ETH_sma,ETH_upper_band,ETH_lower_band,LTC_sma,LTC_upper_band,LTC_lower_band
19,2022-01-01 19:00:00,150.2,150.5,149.6,149.8,5455.057,2022-01-01 19:59:59.999,8.182929e+05,2204.0,2797.406,...,0.0,47003.6430,48566.576701,46554.503299,3718.087,3811.832236,3693.327764,148.200,153.428166,146.971834
20,2022-01-01 20:00:00,149.8,150.6,149.6,150.2,7107.928,2022-01-01 20:59:59.999,1.067106e+06,2462.0,3655.755,...,0.0,47059.2860,48190.018608,46469.561392,3721.656,3802.120140,3693.079860,148.380,152.871156,146.728844
21,2022-01-01 21:00:00,150.2,150.7,149.6,149.7,7806.748,2022-01-01 21:59:59.999,1.172139e+06,2357.0,3375.918,...,0.0,47096.0700,48230.013236,46553.626764,3723.555,3821.611746,3700.428254,148.440,153.484028,146.915972
22,2022-01-01 22:00:00,149.8,150.2,149.4,150.0,5546.299,2022-01-01 22:59:59.999,8.305278e+05,2028.0,2228.700,...,0.0,47123.1460,48139.064385,46500.255615,3724.744,3811.554193,3685.765807,148.520,153.201919,146.398081
23,2022-01-01 23:00:00,150.0,151.0,149.6,150.8,10664.395,2022-01-01 23:59:59.999,1.600667e+06,2502.0,5211.271,...,0.0,47154.5945,48255.544604,46625.935396,3726.218,3824.591925,3691.188075,148.615,153.527259,146.472741

In [86]:
class TradingEnv:
    def __init__(self, balance_amount, balance_unit, trading_fee_multiplier):
        self.balance_amount = balance_amount
        self.balance_unit = balance_unit
        self.buys = []
        self.sells = []
        self.trading_fee_multiplier =  trading_fee_multiplier #VIP level 0, 0.99925 paying fees with BNB
        
    def buy(self, symbol, buy_price, time):
        self.balance_amount = (self.balance_amount / buy_price) * self.trading_fee_multiplier
        self.balance_unit = symbol
        self.buys.append([symbol, time, buy_price])
    
    def sell(self, sell_price, time):
        self.balance_amount = self.balance_amount * sell_price * self.trading_fee_multiplier
        self.sells.append([self.balance_unit, time, sell_price])
        self.balance_unit = 'USDT'

In [87]:
env = TradingEnv(balance_amount=100, balance_unit='USDT', trading_fee_multiplier=0.99925)

In [88]:
for i in range(len(df)):
    if env.balance_unit == 'USDT':
        for symbol in symbols:
            if df[f'{symbol}-USD_Low'].iloc[i] < df[f'{symbol}_lower_band'].iloc[i]: #buy signal
                env.buy(symbol, df[f'{symbol}_lower_band'].iloc[i], df['OpenTime'].iloc[i])
                break

    if env.balance_unit != 'USDT':
        if df[f'{env.balance_unit}-USD_High'].iloc[i] > df[f'{env.balance_unit}_upper_band'].iloc[i]: #sell signal
            env.sell(df[f'{env.balance_unit}_upper_band'].iloc[i], df['OpenTime'].iloc[i])
            
if env.balance_unit != 'USDT':
    env.sell(df[f'{env.balance_unit}_upper_band'].iloc[-1], df['OpenTime'].iloc[-1])

In [89]:
print(f'num_buys: {len(env.buys)}')
print(f'num_sells: {len(env.sells)}')
print(f'ending_balance: {env.balance_amount} {env.balance_unit}')

num_buys: 27
num_sells: 27
ending_balance: 41.11421733725291 USDT